// Mocks generated by Mockito 5.1.0 from annotations
// in assignment/test/http_user_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:assignment/api/http/http_user.dart' as _i2;
import 'package:assignment/api/model/user.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [HttpConnectUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpConnectUser extends _i1.Mock implements _i2.HttpConnectUser {
  MockHttpConnectUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseurl =>
      (super.noSuchMethod(Invocation.getter(#baseurl), returnValue: '')
          as String);
  @override
  set baseurl(String? _baseurl) =>
      super.noSuchMethod(Invocation.setter(#baseurl, _baseurl),
          returnValueForMissingStub: null);
  @override
  _i3.Future<Map<dynamic, dynamic>> registerUser(_i4.UserRegister? user) =>
      (super.noSuchMethod(Invocation.method(#registerUser, [user]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> loginUser(_i4.UserLogin? user) =>
      (super.noSuchMethod(Invocation.method(#loginUser, [user]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> addProfile(_i5.File? profilePicture) =>
      (super.noSuchMethod(Invocation.method(#addProfile, [profilePicture]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> addCover(_i5.File? coverPicture) =>
      (super.noSuchMethod(Invocation.method(#addCover, [coverPicture]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> generateResetToken(
          _i4.passResetToken? user) =>
      (super.noSuchMethod(Invocation.method(#generateResetToken, [user]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> resetPassword(String? resetToken) =>
      (super.noSuchMethod(Invocation.method(#resetPassword, [resetToken]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> getUserOther(String? user_id) =>
      (super.noSuchMethod(Invocation.method(#getUserOther, [user_id]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> changePassword(
          _i4.ChangePassword? passwordData) =>
      (super.noSuchMethod(Invocation.method(#changePassword, [passwordData]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> changeUsername(String? username) =>
      (super.noSuchMethod(Invocation.method(#changeUsername, [username]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> changeEmail(String? email) =>
      (super.noSuchMethod(Invocation.method(#changeEmail, [email]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<Map<dynamic, dynamic>> changePhone(String? phone) =>
      (super.noSuchMethod(Invocation.method(#changePhone, [phone]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i3.Future<Map<dynamic, dynamic>>);
  @override
  _i3.Future<List<dynamic>> getByUsername(String? parameter) =>
      (super.noSuchMethod(Invocation.method(#getByUsername, [parameter]),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i3.Future<List<dynamic>>);
  @override
  _i3.Future<List<dynamic>> getByEmail(String? parameter) =>
      (super.noSuchMethod(Invocation.method(#getByEmail, [parameter]),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i3.Future<List<dynamic>>);
}
